### ISSUE TITLE
fn delay() missing from instrument instance

### ISSUE THREAD

**Issue by nanotechdave** [arc-instruments/pyarc2#2] opened 2022-10-13 11:29 UTC
When calling 
```python
self.arc.delay()
```
from the run() function of the operation instance, an error occurs, saying that 'Instrument' does not have the delay() attribute. 

Ran on Windows 10 Pro, version 21H2

**Comment by foucault** [comment] 2022-10-13 11:44
This is a duplicate of #1

**Closed as completed by foucault** 2022-10-13 11:44 UTC
Labels: duplicate
